# Generated by Django 4.1.2 on 2023-01-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prediction2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("time", models.TimeField(auto_now_add=True)),
                ("text", models.TextField()),
                ("Predicted_Class", models.CharField(max_length=5)),
                ("confidance_score", models.FloatField()),
            ],
        ),
    ]
